### ISSUE TITLE
Failed to get the VQD for query "X"

### ISSUE THREAD

**Issue by theodosc** [Snazzah/duck-duck-scrape#119]
Since Friday 10/02/2023 the library has stopped working, for any query submitted. Below you can find an example of the error stack.

Error: Failed to get the VQD for query "Hello world".
    at getVQD (...\node_modules\duck-duck-scrape\lib\util.js:53:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async search (...\node_modules\duck-duck-scrape\lib\search\search.js:40:15)
  
Maybe the structure of the page is changed or the user-agent is blocked? Are you aware of this issue and willing to proceed with any updates?
Thanks!

**Comment by Snazzah** [comment]
DDG changed the format of the VQD so the package wasn't able to detect it. This is fixed in v2.2.2.

**Comment by ash80** [comment]
I am facing this issue again today in v2.2.3. Should I open a new issue?

**Comment by Snazzah** [comment]
v2.2.4 should work now

**Comment by ash80** [comment]
Hi @Snazzah , it had been working until today. Today I'm again hitting: `Failed to get the VQD for query "X"` issue
