### ISSUE TITLE
main entry is not valid 

### ISSUE THREAD

**Issue by pioucraft** [Snazzah/duck-duck-scrape#120]
when i try to launch any code with this module it says Error: Cannot find module '/home/emmanuel_macron/Documents/programinc/gougoule.ch/server/node_modules/duck-duck-scrape/lib/index.js'. Please verify that the package.json has a valid "main" entry

step to reproduce the bug:
1. install the module
2. try using the exmple code from the readme.md in javascript nodejs
(sorry for bad english )

**Comment by Snazzah** [comment]
Should be fixed in v2.2.3.
