### ISSUE TITLE
an error occurs ('A server error occurred!') when running news search "DDG.searchNews"

### ISSUE THREAD

**Issue by vms200** [Snazzah/duck-duck-scrape#139]
Hi,

I am trying to search for news (using the function "searchNews") and I get an error "A server error occurred!".
This is a new error since this was working a few weeks ago, without any change on my part.

This seems to be the relevant code: 
```

    const urlll = `https://duckduckgo.com/news.js?${(0, util_1.queryString)(queryObject)}`;
    const response = await (0, needle_1.default)('get',urlll , needleOptions);

    if (response.statusCode === 403)
        throw new Error('A server error occurred!');
```

the parameters that seem to trigger this error are

```
let urlll = 'https://duckduckgo.com/news.js?l=en-us&o=json&noamp=1&q=%22Tennis%22+%2Bsport&vqd=4-193033203888750095242464309887669932330&p=1&df=d&s=0'

let needleOptions = undefined 
```

Any thoughts? 
would appreciate help on this issue
Thanks!

**Comment by Snazzah** [comment]
Pretty sure is DuckDuckGo blocking requests from your server, thus the 403 error. Can't really help with that.

**Comment by cnf22** [comment]
well different ip addresses are not working here as well. so it's not a block on my server. 
and also other functions like DDG.searchVideos works perfectly.
Did you try to run it on your own server? did it work for for you?

**Comment by vms200** [comment]
> Pretty sure is DuckDuckGo blocking requests from your server, thus the 403 error. Can't really help with that.

well different ip addresses are not working here as well. so it's not a block on my server.
and also other functions like DDG.searchVideos works perfectly.
Did you try to run it on your own server? did it work for for you?

**Comment by Snazzah** [comment]
It worked fine on one, but not on another, I'd recommend adding headers from a regular browser, since that seems to have worked for another server.

**Comment by KirubaGhoshak** [comment]
```
const options = {
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://duckduckgo.com/'
  },
  follow_max: 5,  // follow up to 5 redirects
  rejectUnauthorized: false  // ignore SSL errors
};
```

this needleOptions is worked for me

**Comment by vms200** [comment]
> ```
> const options = {
>   headers: {
>     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
>     'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
>     'Accept-Language': 'en-US,en;q=0.5',
>     'Referer': 'https://duckduckgo.com/'
>   },
>   follow_max: 5,  // follow up to 5 redirects
>   rejectUnauthorized: false  // ignore SSL errors
> };
> ```
> 
> this needleOptions is worked for me

Working on my localhost. but not on my ubunto server on a droplet with digital ocean. Maybe it's connected to https certificate?

@Snazzah can you please mark it as an open issue?

**Comment by Snazzah** [comment]
This seems like a mixture of issues, untrustworthy requests to DuckDuckGo, bad headers, SSL certs apparently? I'm not sure if there is a fix-all that the library can implement and it might be that there should just be a bunch more headers that make the request trustworthy, which you can provide.

I'm not active in updating this library anyways, and I can't really debug this issue that seems to be host or IP dependent.
