### ISSUE TITLE
Search doesn't respect safesearch setting

### ISSUE THREAD

**Issue by advaith1** [Snazzah/duck-duck-scrape#2]
search() doesn't respect the safeSearch setting. This seems to be because of `safeSearch = -2`, because if I remove the `= -2` then it works.

Also, is there a reason `icon` was removed? (it still seems to be on the npm version though)

**Comment by suushii** [comment]
Hey @advaith1,
I noticed you forked this project and fixed it.
Do you mind submitting a PR?

**Comment by advaith1** [comment]
In my fork I also removed the defaults as that seemed to fix the safesearch issue, but i'll make a new branch with just the icon change.

**Comment by Ryu945** [comment]
I'd like to see this problem fixed as well.  Does this line give a default or does it flat out overwrite the value I enter?

`async search(query, safeSearch = -2, locale = 'us-en') {`


If this line is in error does that also mean this line is in error as well?

`sync image(query, safe = false, locale = 'us-en') {`

and this line?

` async video(query, safe = false, locale = 'us-en') {`

and this line?

` async amazon(query, safe = false) {`


Or is only.the .search line not working?

**Comment by advaith1** [comment]
According to my testing with search it just overwrites the value, I didn't test the other ones.

**Comment by Ryu945** [comment]
Advaith1, for some reason I am not able to create an issue on your branch.   Is your branch available on NPM?  I am not sure when this branch will get updated.

**Comment by advaith1** [comment]
@ryu945 it's not on npm, you'll need to install it from GitHub

Idk why you can't make an issue, maybe because it's a fork

**Comment by Ryu945** [comment]
Would you consider putting your branch on NPM?  Also, I have noticed it has you listed as a contributor.  Does that mean you can make a fix to suushii's code on NPM by changing it on Github here?

**Comment by advaith1** [comment]
1. no point on putting it on npm, you can install it from github with `npm i advaith1/duck-duck-scrape`
2. no, i can't edit the code, but on my fork I removed the default so its not a full fix.

**Comment by Ryu945** [comment]
I noticed your code advaith1 doesn't follow safe search unless I add the line
`&t=lm&ia=web`

**Comment by advaith1** [comment]
I tested it and it used to work, maybe DDG changed something

**Comment by Ryu945** [comment]
Any plans to fix your version?
