### ISSUE TITLE
search returns only 30 results

### ISSUE THREAD

**Issue by mpuz** [Snazzah/duck-duck-scrape#3]
And results are 50% different from what the browser shows. How to paginate?

```const DuckDuckScrape = require("duck-duck-scrape");
const ddg = new DuckDuckScrape();

const searchPromise = ddg.search("put my keywords here", 100);

searchPromise.then(function(data) {
    console.log(data.map(item => item.url));
    console.log(data.length);
})```

**Comment by Snazzah** [comment]
This issue has been marked **stale**. This package has been updated to **v2**!

Look into documentation and usage here: https://duck-duck-scrape.js.org/
