### ISSUE TITLE
image search is not working

### ISSUE THREAD

**Issue by Subhajit25Mondal** [Snazzah/duck-duck-scrape#5]

**Comment by AL1L** [comment]
This is because it's not sending the `vqd` parameter when getting videos and images. Take a look at https://github.com/deepanprabhu/duckduckgo-images-api/issues/1#issuecomment-347428637

**Comment by deepanprabhu** [comment]
Guys, the above bug was fixed with latest code. Lemme know.

**Comment by deepanprabhu** [comment]
please pull the latest code.

**Comment by Snazzah** [comment]
This issue has been marked **stale**. This package has been updated to **v2**!

Look into documentation and usage here: https://duck-duck-scrape.js.org/
