### ISSUE TITLE
Search fails when no rawDescription is available

### ISSUE THREAD

**Issue by wreiske** [Snazzah/duck-duck-scrape#6]
When using https://www.npmjs.com/package/duck-duck-scrape the search will fail if there is no rawDescription in the search result. I noticed this line is different on this repo. Can you please update the node npm?

Line 115:
`rawDescription: $('.result__snippet', result).html().replace(/&amp;/g, '&').replace(/&gt;/g, '>').replace(/&lt;/g, '<').replace(/&apos;/g, "'").replace(/&quot;/g, '"'),`

```W20181024-07:45:43.649(-4)? (STDERR) (node:17361) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
W20181024-07:45:43.650(-4)? (STDERR)     at Array.from.map.result (/Users/../duck-duck-scrape/index.js:115:65)
W20181024-07:45:43.650(-4)? (STDERR)     at Array.map (<anonymous>)
W20181024-07:45:43.650(-4)? (STDERR)     at DDGScraper.search (/Users/../duck-duck-scrape/index.js:112:91)
W20181024-07:45:43.650(-4)? (STDERR)     at <anonymous>
W20181024-07:45:43.650(-4)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:228:7)```

**Comment by Snazzah** [comment]
This issue has been marked **stale**. This package has been updated to **v2**!

Look into documentation and usage here: https://duck-duck-scrape.js.org/
